
name: Deploy stray bin scripts
on:
  push:
    branches:
      - main
    paths:
      - 'bin/*' 

jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y s3cmd
            
      - name: Create s3cmd config
        run: |
          echo "[default]" >> $HOME/.s3cfg
          echo "access_key = ${{ secrets.SPACES_ACCESS_KEY }}" >> $HOME/.s3cfg
          echo "host_base = ams3.digitaloceanspaces.com" >> $HOME/.s3cfg
          echo "host_bucket = %(bucket)s.ams3.digitaloceanspaces.com" >> $HOME/.s3cfg
          echo "secret_key = ${{ secrets.SPACES_SECRET_KEY }}" >> $HOME/.s3cfg
            
      - name: Build and upload
        run: |

            s3cmd put "bin/install.sh" "s3://stray-builds/cli/install.sh"
            s3cmd setacl "s3://stray-builds/cli/install.sh" --acl-public

            s3cmd put "bin/stray" "s3://stray-builds/cli/stray"
            s3cmd setacl "s3://stray-builds/cli/stray" --acl-public
