name: Deploy straylib

on:
  push:
    branches: [ main ]
    paths:
      - 'straylib/setup.py' #Only push when version bumps happen so package versions can be mapped to commits
  pull_request:
    branches: [ main ]
jobs:
  deploy:
    name: Build and push
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.8'
        
      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y s3cmd
            
      - name: Create s3cmd config
        run: |
          echo "[default]" >> $HOME/.s3cfg
          echo "access_key = ${{ secrets.SPACES_ACCESS_KEY }}" >> $HOME/.s3cfg
          echo "host_base = ams3.digitaloceanspaces.com" >> $HOME/.s3cfg
          echo "host_bucket = %(bucket)s.ams3.digitaloceanspaces.com" >> $HOME/.s3cfg
          echo "secret_key = ${{ secrets.SPACES_SECRET_KEY }}" >> $HOME/.s3cfg
            
      - name: Build and upload
        run: |
            pip install wheel
            pushd "straylib/" > /dev/null
            python setup.py bdist_egg --exclude-source-files
            straylib_egg="$(find dist/straylib-*.egg)"
            wheel convert $straylib_egg
            straylib_wheel="$(basename $(find straylib-*.whl))"
            straylib_destination="s3://stray-builds/straylib/$straylib_wheel"
            s3cmd put ${straylib_wheel} "$straylib_destination"
            s3cmd setacl "$straylib_destination" --acl-public
            popd > /dev/null
          
            
    



