name: Deploy integrate

on:
  push:
    branches: [ main ]
    paths:
      - 'straylib/setup.py'
      - 'docker/integrate/**'

jobs:
  deploy:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
          
      - name: Set up QEMU action
        uses: docker/setup-qemu-action@v1
          
      - name: Set up Docker Buildx action
        uses: docker/setup-buildx-action@v1
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: strayrobots/integrate
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./
          platforms: linux/amd64,linux/arm64
          file: ./docker/integrate/Dockerfile
          push: true
          tags: strayrobots/integrate:latest
          cache-from: type=registry,ref=strayrobots/integrate:buildcache
          cache-to: type=registry,ref=strayrobots/integrate:buildcache,mode=max



