name: Deploy calibrate

on:
  push:
    branches: [ main ]
    paths:
      - 'docker/calibrate/*'
      - '.github/workflows/deploy-calibrate.yml'

jobs:
  deploy:
    name: Build and push Docker image
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - name: Log in to Docker Hub
        uses: docker/login-action@f054a8b539a109f9f41c372932f1ae047eff08c9
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}
      
      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: strayrobots/calibrate
      
      - name: Build and push Docker image
        uses: docker/build-push-action@ad44023a93711e3deb337508980b4b5e9bcdc5dc
        with:
          context: ./
          file: ./docker/calibrate/Dockerfile
          push: true
          tags: strayrobots/calibrate:latest
          cache-from: type=registry,ref=strayrobots/calibrate:latest
          cache-to: type=inline



